# Generated by Django 3.0.3 on 2020-07-20 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tokenizer', '0006_v1_keywords'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keywords',
            old_name='session_id',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='keywords',
            old_name='session_index',
            new_name='code_index',
        ),
    ]
