# Generated by Django 3.0.3 on 2020-07-20 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tokenizer', '0007_auto_20200720_1955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keywords',
            old_name='code',
            new_name='key',
        ),
        migrations.RenameField(
            model_name='keywords',
            old_name='code_index',
            new_name='key_index',
        ),
    ]
