# Generated by Django 3.0.3 on 2020-07-29 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokenizer', '0009_keyword_select'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword_select',
            name='neg_keyword',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='keyword_select',
            name='neg_text',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='keyword_select',
            name='neg_text_norm',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='keyword_select',
            name='neg_word_num',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='keyword_select',
            name='pos_keyword',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='keyword_select',
            name='pos_text',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='keyword_select',
            name='pos_text_norm',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='keyword_select',
            name='pos_word_num',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='keyword_select',
            name='rand_order',
            field=models.IntegerField(null=True),
        ),
    ]
